FROM node:alpine

WORKDIR /app

RUN npm i json-server

COPY api/local-db-example.json api/db.json
COPY api/api-key-middleware.js api/api-key-middleware.js

EXPOSE 8080
 
CMD npm run -- json-server --watch ./api/db.json --middlewares ./api/api-key-middleware.js --port 8080